### PR TITLE
qmd template start

### PR DESCRIPTION
**Pull request by petrelharp**
It looks like [quarto](https://quarto.org/docs/get-started/) might be the way to go for writing a notebook that we can render in various contexts. Here's a start; doing
```
quarto preview compute_truth.qmd
```
will get the (live!) html version.

Next step is to use [variables](https://quarto.org/docs/authoring/variables.html) so we can use this to get an html report for the output of an arbitrary crossvalidation.

### CODE REVIEW

**Comment by petrelharp** [comment]
Here's how to get things into a document, looks like: https://quarto.org/docs/computations/parameters.html

**Comment by petrelharp** [comment]
Okay, there's a recommended workflow in `simulation/README.md`; what do you think, @silastittes ?

**Comment by silastittes** [comment]
Oh wow, this seems really neat! I've heard of quarto but haven't played with it yet. I'll take a moment to set things up so I can view things locally then will look at details a bit more.

**Comment by petrelharp** [comment]
I should have put `quarto` and `papermill` in the conda environment, probably.

**Pull request merged**
